# Generated by Django 4.2.13 on 2024-06-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('publish_date', models.DateField()),
                ('category', models.CharField(max_length=32)),
                ('distribution_expense', models.IntegerField()),
            ],
        ),
    ]
